### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by PeeHaa** [PeeHaa/socket-inspect#7]
# messages

- [ ] proxy started
- [ ] client connected
- [ ] server connected
- [ ] client disconnected
- [ ] server disconnected
- [ ] server sent message
- [ ] client sent message

# tls proxy

- [ ] is this doable?

# dynamic proxy

- [ ] tls server
- [ ] dynamic server address

# cli options

- [ ] cli output
- [ ] web interface + addresses

# web interface

- [ ] client name
- [ ] server name
- [ ] proxy output

# html

- [ ] split into files (css+js)

# webserver

- [ ] route / to index.html

# tests

- [ ] fix all tests
